### ISSUE TITLE
update title & favicon

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/fourseasonsangel-web#11]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/30463117/228177606-07954c65-53ab-4d93-8af1-7ffcbd33438d.png">

**Comment by NadhirahIzzati** [comment]
![Screenshot (517)](https://user-images.githubusercontent.com/74038076/229014303-8c57a8a8-44c8-4b6c-9cc8-059e5f243df2.png)
