### ISSUE TITLE
change header picture

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/fourseasonsangel-web#21]
- [ ] suggest a few header design
- [ ] change header quote
- [x] remove watch video button
![image](https://user-images.githubusercontent.com/30463117/229431164-3184ef45-7d61-410a-a0a1-f9c7ec580a57.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (530)](https://user-images.githubusercontent.com/74038076/229686395-353dd87f-0e73-4eba-8799-957df6750f5f.png) on mobile view, but not all of the picture shown.

![Screenshot (529)](https://user-images.githubusercontent.com/74038076/229686473-06fb0982-a47a-41a2-96a3-5935172dc64e.png) on mobile view, all of the picture is shown.
