### ISSUE TITLE
suggest icons for treatments

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/fourseasonsangel-web#41]
do not commit yet, find suitable icons and change the web view to be able to review. can find icons from https://www.flaticon.com/

![image](https://github.com/phisoft/fourseasonsangel-web/assets/30463117/13c44388-5459-4000-a776-352522817719)

**Comment by NadhirahIzzati** [comment]
choice 1:
![Screenshot (781)](https://github.com/phisoft/fourseasonsangel-web/assets/74038076/2c67c5ce-82c3-400e-88cf-e921ee07ba4b)

choice 2:
![Screenshot (782)](https://github.com/phisoft/fourseasonsangel-web/assets/74038076/e2374c18-d6ea-4f80-b05c-f2956111557a)

**Comment by rosclaritha** [comment]
@NadhirahIzzati give more suggestions, maybe can try to change color of the icon

**Comment by NadhirahIzzati** [comment]
![Screenshot (796)](https://github.com/phisoft/fourseasonsangel-web/assets/74038076/1c9795b5-382b-44c4-a766-135bc5e29db4)
![Screenshot (797)](https://github.com/phisoft/fourseasonsangel-web/assets/74038076/a461dbcd-66dc-420d-babd-7230e3b7af74)
![Screenshot (792)](https://github.com/phisoft/fourseasonsangel-web/assets/74038076/172a175d-7be9-47cc-b007-b5f3c809b1c8)
![Screenshot (793)](https://github.com/phisoft/fourseasonsangel-web/assets/74038076/4582ce29-09d2-4985-b947-6b91561162b2)
