### ISSUE TITLE
Some sample brochure

### ISSUE THREAD

**Issue by paragasu** [phisoft/fourseasonsangel-web#8]
![image](https://user-images.githubusercontent.com/27353/228092320-e18a8c84-3e05-4b28-aa3c-b42840413864.png)
![image](https://user-images.githubusercontent.com/27353/228092335-c51e8b91-fc28-49d4-9bf4-21ba73fb4280.png)
![image](https://user-images.githubusercontent.com/27353/228092347-5f7af836-3213-4e5c-8d76-7c198b172580.png)
![image](https://user-images.githubusercontent.com/27353/228092358-2eacc80c-f78d-4502-8c9a-665ad2038a46.png)
![image](https://user-images.githubusercontent.com/27353/228092372-bf91bc41-cdb2-449e-8237-e5bb38fbb41a.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (519)](https://user-images.githubusercontent.com/74038076/229014682-49a103c8-28dc-4b56-af17-031eb30bc00e.png)
