### ISSUE TITLE
upload logo & company color theme

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/fourseasonsangel-web#9]
![image](https://user-images.githubusercontent.com/30463117/228177711-142b1ea9-aaf4-488a-9ac7-9df0112701eb.png)

**Comment by NadhirahIzzati** [comment]
![Untitled design](https://user-images.githubusercontent.com/74038076/228468035-e1c1d0d9-0220-494d-a922-b038e7c3e827.png)

**Comment by NadhirahIzzati** [comment]
![Screenshot (518)](https://user-images.githubusercontent.com/74038076/229014400-c18a0d3c-ea9e-4dcf-ac0b-5b3f08b4c6b5.png)
